### ISSUE TITLE
Tear this idea down (please)

### ISSUE THREAD

**Issue by ar4s-eth** [kpreid/all-is-cubes#239]
Hi Kevin,

Apologies in advance for hitting you with a massively naive question,

I came across your project while researching ML/DL/RL training models, data structures and voxels... in the hope that proven models could either be encoded or compressed/encrypted as a in-game primitive or expression. 

I'v recently re-skilled as a dev but would be interested to find a novel way to have cubes be an abstraction of a more valuable dataset. 

Hope that makes sense, and if you understand and it's possible - I'll have an excuse to learn rust! :)

**Comment by kpreid** [comment]
I'm not at all sure what you're asking. I don't know what it would mean for a ML model to be encoded as voxels (in a meaningful way — obviously any digital data _can_ be visualized in 3D, whether or not that's _useful_), or what you mean by “an abstraction of a more valuable dataset”.

I'm open to interesting ideas to explore, but they need to be more concretely defined ones, like “[specific data type] can be loaded into All is Cubes with the result that [specific thing happens in the simulation]”. My todo list is very long already!
