### ISSUE TITLE
The streetlights hides the text

### ISSUE THREAD

**Issue by CatCode79** [kpreid/all-is-cubes#400]
When text is in the same area of ​​the screen as the street lamp, the latter covers the text, as shown in the image

![image](https://github.com/kpreid/all-is-cubes/assets/12321983/add234ab-23e3-47dc-85e9-58356fb66541)

**Comment by kpreid** [comment]
Should be fixed for now by 0ef26df3e7625e8f52cac6fa1bb40a7f8ba97e0b — the shadow will now be strong enough for the text to be readable. There's room for more improvement, but I want to tackle having proper HDR-to-SDR tone mapping before trying to polish the text.

![image](https://github.com/kpreid/all-is-cubes/assets/779501/a9a6d77c-07be-436e-ad89-189bcb7b4aa4)
